[문제-1] 길이가 10인 0-벡터를 만드세요.

In [12]:
import numpy as np
a = np.zeros(10, dtype='int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [2]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [11]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [6]:
a = np.arange(49, 9, -1)
print(a)
r = a[::-1]
r = np.flip(a)
print(r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [15]:
a = np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [8]:
a = np.array([1,2,0,0,4,0])
result = a!=0
print(a[result])  # = print(a[a != 0])

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [9]:
a = np.identity(3)
print(a)

b = np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [14]:
a = np.random.rand(3,3)
print(a)

[[0.32276219 0.44349907 0.67252676]
 [0.45442416 0.20414831 0.83511352]
 [0.42612354 0.29038694 0.03987033]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [16]:
print(np.max(a))
print(np.min(a))

0.8351135199961846
0.039870325594548395


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [17]:
row_ave = np.average(a, axis=1)
col_ave = np.average(a, axis=0)
print('행평균:', row_ave, '열평균:', col_ave)

행평균: [0.47959601 0.49789533 0.25212694] 열평균: [0.4011033  0.31267811 0.51583687]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [27]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [18]:
b = np.random.randint(10, 50, 9)
print(b)

[26 23 39 37 25 17 34 35 20]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [19]:
c = b.reshape((3,3))
print(c)

[[26 23 39]
 [37 25 17]
 [34 35 20]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [20]:
print(c.sum(axis=1))
print(np.sum(c, axis=1))

[88 79 89]
[88 79 89]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [21]:
print(c.max(axis=0))
print(np.max(c, axis=0))

[37 35 39]
[37 35 39]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [22]:
print(c.mean())
print(np.average(c))

28.444444444444443
28.444444444444443


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [29]:
c = np.random.randint(1, 11, (2,3))
print(c)

[[2 7 5]
 [6 3 5]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [28]:
j = np.random.randint(10, 21, (3,2))
print(j)

[[13 11]
 [11 11]
 [13 20]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [31]:
print(np.matmul(c,j))
print(c@j)
print(np.dot(c,j))
d = np.dot(c,j)

[[168 199]
 [176 199]]
[[168 199]
 [176 199]]
[[168 199]
 [176 199]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [32]:
print(d.T)
print(np.transpose(d))

[[168 176]
 [199 199]]
[[168 176]
 [199 199]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [33]:
# lotto = np.random.randint(1, 47)
# r = np. random.choice(lotto, size=(6,), replace=False)
# print(r)

lotto = np.random.choice(np.arange(1,47), 6, replace=False)
print(lotto)

[20 21 45  5  6 36]
